apiVersion: v1 
kind: Namespace
metadata:
    name: backend-team

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-backend
  namespace: backend-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-backend
  template:
    metadata:
      labels:
        app: personal-backend
    spec:
      containers:
        - name: personal-backend
          image:  cotishq/personal-backend:1
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@db.default.svc.cluster.local:5432/postgres?sslmode=disable
            
---
apiVersion: v1
kind: Service
metadata:
  name: personal-backend
  namespace: backend-team
spec:
  selector:
    app: personal-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP